###
### Box cutter & PSF fitting parameters

# Output directory. Note: this gets overridden if a command
# line argument "-outdir" is passed.
outdir: "/n23data1/mccleary/real_images/20mas_resamp_working/"

# Augment galaxy catalog with PSFs ("True") or just star catalog ("False")?
augment_galcat: True

input_catalog:
  hdu: 2
  x_key: 'X_IMAGE'
  y_key: 'Y_IMAGE'
  psf_x_key: 'XWIN_IMAGE'
  psf_y_key: 'YWIN_IMAGE'
  ra_key: 'ALPHAWIN_J2000'
  dec_key: 'DELTAWIN_J2000'
  ra_units: 'deg'
  dec_units: 'deg'
  ## Next set of params is for diagnostics calculation
  flux_key: 'FLUX_AUTO'
  # Leave err_image_key blank if catalog has no ERR image (assumed units = std)
  err_image_key: 'ERR_VIGNET'

# Pixel scale of image for PSF diagnostics
pixel_scale: 0.02
# Box (vignette) size for all object/psf/weight images
box_size: 101

# Cutouts to add to output catalog
cutout_list:
  hdu: [2]
  extname: ["ERR"]

# For SExtractor and PIFF
weight_image:
  hdu: 4
  type: "MAP_WEIGHT"

# Science exposure is usually 0th or 1th extension
sci_image:
  hdu: 1

# What kind of PSFs to create and add to star catalog?
psf_models:
  psfex: True
  webbpsf: False
  piff: False
  mirage: False
  single: False
  shopt: True
  
# Make a WebbPSF model from scratch?
webb_psf:
  # Make WebbPSF? True or False.
  make_webb_psf: False
  # Oversample long-wavelength channel PSFs?
  oversample_lw: False

# Split stars into training and validation sub-samples for PSF fitting?
split_stars_validation_training: True

# Location of SEx/PIFF/PSFEx config files
astro_config_dir: '/n23data1/mccleary/cweb_psf/src/astro_config/'

# Reference an external star catalog or parameters
star_param_file: '/n23data1/mccleary/cweb_psf/configs/20mas_mosaics_star_params.yaml'
