###
### Box cutter parameters
input_catalog:
  hdu: 2
  x_tag: 'XWIN_IMAGE'
  y_tag: 'YWIN_IMAGE'
  ra_tag: 'ALPHAWIN_J2000'
  dec_tag: 'DELTAWIN_J2000'
  ra_units: 'deg'
  dec_units: 'deg'

# Box size for all images
box_size: 131

# For mosaic i2d structure
weight_image:
  hdu: 4

# For i2d structure
err_image:
  hdu: 2

# Science exposure is usually 0th or 1th extension
sci_image:
  hdu: 1

# Location of SEx/PIFF/PSFEx config files
astro_config_dir: 'astro_config/'

# Output directory (will be created within image directory)
outdir: 'gal_cutout_working/'

# Reference an external star catalog or parameters
star_param_file: 'configs/star_params.yaml'
