###
### Box cutter & PSF fitting parameters

# Output directory
outdir: "./gal_cutout_working"

# Augment galaxy catalog with PSFs ("True") or just star catalog ("False")?
augment_galcat: False

input_catalog:
  hdu: 2
  x_key: 'X_IMAGE'
  y_key: 'Y_IMAGE'
  psf_x_key: 'XWIN_IMAGE'
  psf_y_key: 'YWIN_IMAGE'
  ra_key: 'ALPHAWIN_J2000'
  dec_key: 'DELTAWIN_J2000'
  ra_units: 'deg'
  dec_units: 'deg'

# Box size for all images
box_size: 101

# Cutouts to add to output catalog
cutout_list:
  hdu: [2]
  extname: ["ERR"]

# For SExtractor and PIFF
weight_image:
  hdu: 4
  type: "MAP_WEIGHT"

# Science exposure is usually 0th or 1th extension
sci_image:
  hdu: 1

# What kind of PSFs to create and add to star catalog?
psf_models:
  psfex: True
  webbpsf: False
  piff: False
  mirage: False
  single: True

# I don't love this: directory for making Marko-style PSFs.
# Should at least add config error-checking.
single_psf:
  psf_dir: '/n17data/shuntov/PSFEx_work/PSF_JWST_COSMOS-Web/'
  # filt and tile will get replaced with filter and tile!
  # should have format like 'JWST-PSFEx_out_filt_tile_psf_v4.0.psf', with literally filt and tile where desired
  basename: 'JWST-PSFEx_out_filt_tile_psf_v4.0.psf'

# Make a WebbPSF model?
webb_psf:
  # Make WebbPSF? True or False.
  make_webb_psf: False
  # Oversample long-wavelength channel PSFs?
  oversample_lw: False

# Split stars into training and validation sub-samples for PSF fitting?
split_stars_validation_training: True

# Location of SEx/PIFF/PSFEx config files
astro_config_dir: '/n23data1/mccleary/cweb_psf/src/astro_config/'

# Reference an external star catalog or parameters
star_param_file: '/n23data1/mccleary/cweb_psf/configs/real_mosaics_star_params.yaml'
