###
### Box cutter & PSF fitting parameters

# Output directory
#outdir: "./psf_diagnostics"
outdir: "/n23data1/mccleary/real_data/Jan2024/psf-diagnostics"
input_catalog:
  hdu: 1
  psf_x_key: 'XWIN_IMAGE'
  psf_y_key: 'YWIN_IMAGE'
  ra_key: 'ALPHAWIN_J2000'
  dec_key: 'DELTAWIN_J2000'
  ra_units: 'deg'
  dec_units: 'deg'
  flux_key: 'FLUX_AUTO'
  # Leave err_image_key blank if catalog has no ERR image (assumed units = std)
  err_image_key: 'ERR_VIGNET'

# Box (aka stamp aka vignette) size for all star-psf models
box_size: 101

# Image pixel scale to be using
pixel_scale: 0.03

# What kind of PSFs to model?
psf_models:
  psfex: True
  webbpsf: False
  piff: False
  mirage: False
  single: True


# Cutouts to add to output catalog
cutout_list:
  hdu: [2]
  extname: ["ERR"]
